config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'

  resources :users

  root 'main#home'

  get 'home'    => 'main#home'
  get 'contact' => 'main#contact'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  post 'downvote' => 'sessions#downvote'
  post 'upvote' => 'sessions#upvote'
  post 'toggleFav' => 'sessions#toggleFav'

  post 'feedbacks' =>'feedback#create'

  get 'search-articles' => 'search#search_articles'

  get 'yikesydikes', to: 'authors#new', as: :new_author
  post 'yikesydikes', to: 'authors#create', as: :post_author
  get '/authors/:id', to: 'authors#show', as: :author

  resources :articles do
    resources :comments, only:[:create, :destroy]
  end

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles

  before_save { self.email = email.downcase}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { in:4..30 }
  validates :email, presence: true, length: {in:4...200},
            format: { with:VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {in:6..100}
  validates :password_confirmation, presence: true, length: {in:6..100}
  has_secure_password

  # Returns hash digest of a given string
  def Author.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create( string, cost: cost)
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_filter :url_hack, only: [:show]

  def new
    @author = Author.new
    @author.authenticated = false
  end

  def show
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new( author_params)
    if @author.save
      log_in @author
      redirect_to @author
    else
      render 'authors/new'
    end
  end

  private
    def author_params
      params.require(:author).permit(:name, :email, :password, :about,
              :email ,:password_confirmation)
    end

    def url_hack
      unless params[:id].to_i == session[:user_id] || params[:id].to_i ==
          session[:author_id]
        # This line redirects the user to the previous action
        unless session[:user_id] || session[:author_id]
          flash[:warning] = 'Please log in!'
        else
          flash[:warning] = 'Dear user! Please mind your own!'
        end
        redirect_to root_path
      end
    end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_error_messages.html.erb
<% if @author.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      There are <%= pluralize( @author.errors.count, 'error')  %>
    </div>
    <ul class="list-group panel-body">
      <% @author.errors.full_messages.each do |msg| %>
          <li class="list-unstyled alert-danger list-group-item"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/authors/new.html.erb
<%= provide( :title, "New Author") %>

<div class="container">
  <h3 class="lead lead_text">New (secret) Author Signup</h3>

  <%= render 'error_messages' %>

  <%# NEW LEARN url:path for posting to a custom path %>

  <%= form_for @author, url: new_author_path,
               html: {class: "col-md-offset-2 col-md-3"} do |f| %>

    <%= f.text_field :name, class: "form-control", placeholder: "Name*" %>
    <%= f.text_area :about, class: "form-control",
                    placeholder: "Tell us a bit about yourself" %>
    <%= f.email_field :email, class: "form-control", placeholder: "Email*"%>
    <%= f.password_field :password, class: "form-control", placeholder:
                                     "Password*" %>
    <%= f.password_field :password_confirmation, class: "form-control",
                    placeholder: "Confirm Password*" %>

    <%= f.submit "Sign me up!", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/authors/show.html.erb
<%= provide(:title, "Author Profile")%>

<style>
  h4 > strong {
    font-family: 'Indie Flower', cursive;
  }
</style>

<h2 class="mdl-typography--title main_heading"><%= @author.name %></h2>
<div class="mdl-grid">
  <div class="mdl-cell--2-col"></div>
  <div class="mdl-cell--8-col mdl-color--cyan-100">
    <h4 class="text-left mdl-color--cyan-100">
      <strong>About Author</strong>
    </h4>
    <pre class="mdl-color--cyan-100">
      <%= @author.about %>
    </pre>
  </div>
</div>