config/routes.rb
Rails.application.routes.draw do
  get 'feedback/new'

  resources :users

  root 'main#home'

  get 'home'    => 'main#home'
  get 'contact' => 'main#contact'
  get 'login'   => 'sessions#new'
  post 'login'  => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

  post 'downvote' => 'sessions#downvote'
  post 'upvote' => 'sessions#upvote'
  post 'toggleFav' => 'sessions#toggleFav'

  post 'feedbacks' =>'feedback#create'

  get 'search-articles' => 'search#search_articles'

  get 'yikesydikes', to: 'authors#new', as: :new_author
  post 'yikesydikes', to: 'authors#create', as: :post_author
  get '/authors/:id', to: 'authors#show', as: :author

  resources :articles do
    resources :comments, only:[:create, :destroy]
  end

end

app/views/layouts/_header.html.erb
<!-- Always shows a header, even in smaller screens. -->
<header class="mdl-layout__header mdl-layout__header--seamed">
  <div class="mdl-layout__header-row">
    <div class="mdl-layout__drawer-button mdl-color--indigo">
      <i class="material-icons">menu</i>
    </div>

    <!-- Title -->
    <span class="mdl-layout-title">Blog Name</span>
    <a style="text-decoration: none; margin-left: 1%;" href="/"
       class="mdl-button
    mdl-js-button
        mdl-button--icon">
      <i class="material-icons">home</i>
    </a>

    <div class="mdl-layout-spacer"></div>

    <!-- Search button -->
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
                  mdl-textfield--floating-label mdl-textfield--align-right"
          id="search-div"
    >
      <label class="mdl-button mdl-js-button mdl-button--icon"
             for="search-text-field">
        <i class="material-icons">search</i>
      </label>
      <div class="mdl-textfield__expandable-holder">
        <input class="mdl-textfield__input" type="text" name="sample"
               id="search-text-field"
               onkeydown="if (event.keyCode == 13) { s(); }"
        >
      </div>
    </div>

    <!-- Add spacer, to align navigation to the right -->
    <!--<div class="mdl-layout-spacer"></div>-->


    <!-- Navigation. We hide it in small screens. -->
    <nav class="mdl-navigation mdl-layout--large-screen-only">
      <%= link_to "Home", root_path ,id:'navHome', class:
                                "mdl-navigation__link" %>
      <%= link_to 'Posts', articles_path,id:'navList', class:
                                 "mdl-navigation__link" %>
      <%= link_to 'Contact', contact_path,id:'navContact', class:
                                   "mdl-navigation__link" %>
      <% if logged_in? %>
        <% if current_author %>
          <%= link_to "New Post",   new_article_path ,id:'newArticle',class:
                                       "mdl-navigation__link"  %></li>
         <% end %>
        <button id="menu-author" class="mdl-button mdl-js-button
        mdl-button--icon">
          <i class="material-icons">more_vert</i>
        </button>
        <ul class="mdl-menu mdl-color--indigo-300 mdl-menu--bottom-right
        mdl-js-menu
        mdl-js-ripple-effect"
            for="menu-author">
          <li>
            <% if current_author %>
              <%= link_to "Profile",current_author ,id:'account',
                          class:"mdl-menu__item" %>
              <% else %>
              <%= link_to "Profile",current_user ,id:'account',
                          class:"mdl-menu__item" %>
          <% end %>
          </li>
          <li class="">
            <%= link_to "Log Out",logout_path ,
                        class:"mdl-menu__item" %>
          </li>
          <li class="">
            <%= link_to "Another Option", "",
                        class:"mdl-menu__item" %>
          </li>
        </ul>

      <% else  %>
        <%= link_to "Sign In / Up",   login_path ,id:'signIn',class:
                                     "mdl-navigation__link"  %></li>
      <% end %>
    </nav>
  </div>
</header>
<div class="mdl-layout__drawer mdl-color--lime-400">
  <span class="mdl-layout-title mdl-color--red">Navigation</span>
  <nav class="mdl-navigation">
    <%= link_to "Home", root_path ,class:
                              "mdl-navigation__link" %>
    <%= link_to "Search", search_articles_path ,class:
                              "mdl-navigation__link" %>
    <%= link_to 'Posts', articles_path, class:
                               "mdl-navigation__link" %>
  </nav>
  <span class="mdl-layout-title mdl-color--red">User Options</span>
  <nav class="mdl-navigation">
    <% if logged_in? %>
    <%= link_to "Favourites", "", class:
                              "mdl-navigation__link" %>
    <%= link_to 'Bookmarks', "", class:
                               "mdl-navigation__link" %>
    <div>
      <% if current_author %>
        <%= link_to "Profile",current_author ,
                    class:"mdl-navigation__link" %>
      <% else %>
        <%= link_to "Profile",current_user ,
                    class:"mdl-navigation__link" %>
      <% end %>
    </div>
    <%= link_to 'Logout', logout_path, class:
                                   "mdl-navigation__link" %>

    <% else%>
    <%= link_to 'Log In', login_path, class:
                                "mdl-navigation__link" %>
  </nav>
  <% end %>
  <span class="mdl-layout-title mdl-color--red">Other Options</span>
  <nav class="mdl-navigation">
    <%= link_to 'Contact', contact_path, class:
                                 "mdl-navigation__link" %>
    <%= link_to 'Feedback', "/feedback/new", class:
                                 "mdl-navigation__link" %>
  </nav>
</div>



<script type="text/javascript">
  function s() {
    var form = $('<form></form>');

    form.attr("method", "get");
    form.attr("action", "/search-articles");

    var field = $('<input></input>');
    field.attr("type", "hidden");
    field.attr("name", "q");
    field.attr("value", $('#search-text-field').val() );
    form.append(field);

    $(document.body).append(form);
    form.submit();
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="mdl-layout mdl-js-layout">
  <%= render 'layouts/header' %>
  <main class="mdl-layout__content">
    <div class="page-content">
      <div class="mdl-grid">
        <div class="mdl-cell--1-col"></div>
        <div class="mdl-cell--10-col">
          <!-- Your content goes here -->
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
          <% end %>
          <%= yield %>
          <%= debug(params) if Rails.env.development? %>
        </div>
      </div>
    </div>
  </main>
</div>
<script type="text/javascript">
  componentHandler.upgradeDom();
</script>
</body>
</html>